# Generated by Django 4.1.4 on 2022-12-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Вин'),
        ),
    ]
